var trophyData = [
    {
        "rally": "49",
        "year": "2026",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "-",
        "jj_kineally": "-",
        "friendship": "-",
        "bob_hughes": "-",
        "ann_clarke": "-",
        "newman": "-",
        "jimmy_leyden": "",
        "dennis_byrne": "-",
        "finton_harold": "-",
        "mccormack": "-",
        "dennis_juba": "-",
        "westpark": "-",
        "eric_timon": "",
        "tavern": "-",
        "scarriff": "-",
        "jh_stimpson": "-",
        "benson": "-",
        "church_bay": "-",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "-",
        "dave_mccabe": "-"
    },
    {
        "rally": "48",
        "year": "2025",
        "estemaid": "",
        "boyle": "Cara",
        "benjamin": "Dunross",
        "nm_barge": "Fleur De Lys",
        "wynn_juba": "Geraldine & Aoife Burke 68M",
        "jj_kineally": "John Paul II, Cara, 69M, Aurora, Cassandra, Dunross",
        "friendship": "Dot Campbell",
        "bob_hughes": "Ellis Family Virginia Lady",
        "ann_clarke": "Rhys Byrne Connick Desperado",
        "newman": "Cassandra",
        "jimmy_leyden": "",
        "dennis_byrne": "Carmel Byrne Desperado",
        "finton_harold": "-",
        "mccormack": "Emily McGrory Voyager",
        "dennis_juba": "Brislane Family Gallifrey",
        "westpark": "Dunross",
        "eric_timon": "",
        "tavern": "E. McGrory",
        "scarriff": "-",
        "jh_stimpson": "-",
        "benson": "Peter Hanna Lady Penlyric",
        "church_bay": "Hamill Family, Aurora",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "Anu O Donovan Trivial Pursuit",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "47",
        "year": "2024",
        "estemaid": "",
        "boyle": "Birling",
        "benjamin": "Ivan Mullins",
        "nm_barge": "Seachran",
        "wynn_juba": "Birling",
        "jj_kineally": "Auburn, Chang Sha, Gallifrey, Murano, 33M",
        "friendship": "Emily Becker",
        "bob_hughes": "McGrath Family Mo Cheol Thu",
        "ann_clarke": "Anu O Donovan Mallory II",
        "newman": "-",
        "jimmy_leyden": "",
        "dennis_byrne": "Sophie Dillon Affaja",
        "finton_harold": "-",
        "mccormack": "Shirley Mullins Panga",
        "dennis_juba": "Markie Becker 74M",
        "westpark": "A. Curtin Miss Chief",
        "eric_timon": "",
        "tavern": "L. Thornbury",
        "scarriff": "Samson",
        "jh_stimpson": "Charlie Dunn",
        "benson": "Ornait Bayly Beccles",
        "church_bay": "Hanna Family, Lady Penlyric",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "Anu O Donovan Mallory II",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "46",
        "year": "2023",
        "estemaid": "",
        "boyle": "J. MacFarlane ParadijsVogel",
        "benjamin": "Dunross",
        "nm_barge": "-",
        "wynn_juba": "Anna Lindley & Ellie McAleer Lady Lydia",
        "jj_kineally": "EOS, Gallifrey, Miss Chief, 72M",
        "friendship": "Taylor Williams",
        "bob_hughes": "Jimmy MacFarlane ParadijsVogel",
        "ann_clarke": "-",
        "newman": "Samson",
        "jimmy_leyden": "David Garland",
        "dennis_byrne": "Steven Wade Linquenda",
        "finton_harold": "-",
        "mccormack": "Aysha Brislane Gallifrey",
        "dennis_juba": "Aoife Geraghty Linquenda",
        "westpark": "C. Corcoran",
        "eric_timon": "",
        "tavern": "J. MacFarlane",
        "scarriff": "John Shanice",
        "jh_stimpson": "-",
        "benson": "Anu O Donovan Mallory II",
        "church_bay": "Fitzsimons Family, Monah",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "Aysha Brislane Gallifrey",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "45",
        "year": "2022",
        "estemaid": "",
        "boyle": "Mary Byrne 72M",
        "benjamin": "A Lindley Lady Lydia",
        "nm_barge": "Cara",
        "wynn_juba": "-",
        "jj_kineally": "4B, Gracious Lady, John Paul II, Trivial Pursuit, West One, Yachts of Fun",
        "friendship": "Chris McPhail",
        "bob_hughes": "Deadly Buzz & Crew",
        "ann_clarke": "Adam Leonard",
        "newman": "My Obsession",
        "jimmy_leyden": "Leahy Family, John Paul II",
        "dennis_byrne": "Daniela Leahy John Paul II",
        "finton_harold": "-",
        "mccormack": "Arlene Brislane Gallifrey",
        "dennis_juba": "-",
        "westpark": "P Nolan Tinca Tinca",
        "eric_timon": "",
        "tavern": "C. Burke 69M",
        "scarriff": "4E",
        "jh_stimpson": "-",
        "benson": "Louise Thornbury Auburn",
        "church_bay": "Williams Family",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "Emily McGrory",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "-",
        "year": "2021",
        "estemaid": "No Rally (COVID)",
        "boyle": "No Rally (COVID)",
        "benjamin": "No Rally (COVID)",
        "nm_barge": "No Rally (COVID)",
        "wynn_juba": "No Rally (COVID)",
        "jj_kineally": "No Rally (COVID)",
        "friendship": "No Rally (COVID)",
        "bob_hughes": "No Rally (COVID)",
        "ann_clarke": "No Rally (COVID)",
        "newman": "No Rally (COVID)",
        "jimmy_leyden": "No Rally (COVID)",
        "dennis_byrne": "No Rally (COVID)",
        "finton_harold": "No Rally (COVID)",
        "mccormack": "No Rally (COVID)",
        "dennis_juba": "No Rally (COVID)",
        "westpark": "No Rally (COVID)",
        "eric_timon": "No Rally (COVID)",
        "tavern": "No Rally (COVID)",
        "scarriff": "No Rally (COVID)",
        "jh_stimpson": "No Rally (COVID)",
        "benson": "No Rally (COVID)",
        "church_bay": "No Rally (COVID)",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "No Rally (COVID)",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "-",
        "year": "2020",
        "estemaid": "No Rally (COVID)",
        "boyle": "No Rally (COVID)",
        "benjamin": "No Rally (COVID)",
        "nm_barge": "No Rally (COVID)",
        "wynn_juba": "No Rally (COVID)",
        "jj_kineally": "No Rally (COVID)",
        "friendship": "No Rally (COVID)",
        "bob_hughes": "No Rally (COVID)",
        "ann_clarke": "No Rally (COVID)",
        "newman": "No Rally (COVID)",
        "jimmy_leyden": "No Rally (COVID)",
        "dennis_byrne": "No Rally (COVID)",
        "finton_harold": "No Rally (COVID)",
        "mccormack": "No Rally (COVID)",
        "dennis_juba": "No Rally (COVID)",
        "westpark": "No Rally (COVID)",
        "eric_timon": "No Rally (COVID)",
        "tavern": "No Rally (COVID)",
        "scarriff": "No Rally (COVID)",
        "jh_stimpson": "No Rally (COVID)",
        "benson": "No Rally (COVID)",
        "church_bay": "No Rally (COVID)",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "No Rally (COVID)",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "44",
        "year": "2019",
        "estemaid": "",
        "boyle": "Panga Tom Mulcahy",
        "benjamin": "G Burke 68M",
        "nm_barge": "Cara",
        "wynn_juba": "Neasa & Tadhg O Cionnaithe",
        "jj_kineally": "Lady Lydia, Leitrim Star, Chang Sha, Affaja, Eimear C, Lady Anne III",
        "friendship": "Eoin O Reilly, Myls",
        "bob_hughes": "Ellis Family Virginia Lady",
        "ann_clarke": "Brian O'Reilly Myls",
        "newman": "-",
        "jimmy_leyden": "Thread Softly, Nedzey Rose and Crew",
        "dennis_byrne": "Sophie Dillon Affaja",
        "finton_harold": "-",
        "mccormack": "Olivia Egan Seacat",
        "dennis_juba": "Eimear Boyle & James Daniels",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "A. Burke 33M",
        "scarriff": "92E",
        "jh_stimpson": "-",
        "benson": "Niamh Byrne 72M",
        "church_bay": "McGrath Family",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "Ailish Kearney-Boyle",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "43",
        "year": "2018",
        "estemaid": "",
        "boyle": "Palo Alto Dave Saunders",
        "benjamin": "Tanjuan",
        "nm_barge": "Cara",
        "wynn_juba": "Susan & Ruairi O Brolchain Birling",
        "jj_kineally": "Myls, Kerry Jane, 68M, 69M, Dunross",
        "friendship": "Ivan Mullins",
        "bob_hughes": "41M Les Saunders & Yvonne Duffy",
        "ann_clarke": "Emily Becker 74M",
        "newman": "Caja",
        "jimmy_leyden": "Connon Crew, Rambler",
        "dennis_byrne": "David Garland Izzymar",
        "finton_harold": "-",
        "mccormack": "Eibhlin Smith Coreibh",
        "dennis_juba": "Aoife & Fergus Curtin",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "G. Burke 68M",
        "scarriff": "Rambler",
        "jh_stimpson": "D & H McDermott",
        "benson": "Hannes Leahy John Paul II",
        "church_bay": "Leahy Family, John Paul II",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "Aoife Geraghty Kerry Jane",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "42",
        "year": "2017",
        "estemaid": "",
        "boyle": "Ben Tracey 92E",
        "benjamin": "Cosmea",
        "nm_barge": "Serpa",
        "wynn_juba": "Anne & Ray Molloy Stravaiger",
        "jj_kineally": "Affaja, Coreibh, Deadly Buzz, Float No. 1, Shanice",
        "friendship": "Aoife Burke",
        "bob_hughes": "Geraghty Family Affaja",
        "ann_clarke": "Anna Lindley Lady Lydia",
        "newman": "Kittiwake",
        "jimmy_leyden": "",
        "dennis_byrne": "-",
        "finton_harold": "-",
        "mccormack": "Aoife Geraghty Kerry Jane",
        "dennis_juba": "Crew of Stravaiger",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "C. Morgan",
        "scarriff": "De Eems",
        "jh_stimpson": "-",
        "benson": "Cian Molloy Stravaiger",
        "church_bay": "Daniels Family, Carpe Diem",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "Denise Byrne Mistral",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "41",
        "year": "2016",
        "estemaid": "",
        "boyle": "Joe & Eirinn Leonard Shanice",
        "benjamin": "Teanna Tinca Tinca",
        "nm_barge": "Shanice",
        "wynn_juba": "Crew of Crews Inn",
        "jj_kineally": "Chenoa, Mutual Admiration, 74M, Oscar, IZZIMAR",
        "friendship": "Will Ellis",
        "bob_hughes": "41M Les Saunders & Yvonne Duffy",
        "ann_clarke": "Aoibhe Harney Elizabeth Anne",
        "newman": "Lady Diva",
        "jimmy_leyden": "",
        "dennis_byrne": "-",
        "finton_harold": "-",
        "mccormack": "A Dwane 74M",
        "dennis_juba": "J. Boyle A. Boyle & J. Brislane",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "-",
        "scarriff": "-",
        "jh_stimpson": "-",
        "benson": "Ashton Brandt Kittiwake",
        "church_bay": "Molloy Family, Stravaiger",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "40",
        "year": "2015",
        "estemaid": "",
        "boyle": "Daniel Burke 77M",
        "benjamin": "Coreibh",
        "nm_barge": "Trust Me Scout",
        "wynn_juba": "Lady Lydia Rebecca Lindley, Joe David Earle, Aoife Geraghty",
        "jj_kineally": "Corona, Dunross, Seagull, 4B",
        "friendship": "Alan Lindley",
        "bob_hughes": "Teanna-Tinca, Colm & Anna Burke, Pat Nolan",
        "ann_clarke": "Rebecca Lindley Lady Lydia",
        "newman": "Come on Eileen",
        "jimmy_leyden": "O'Brien Family, Corona",
        "dennis_byrne": "-",
        "finton_harold": "-",
        "mccormack": "Niamh O Doherty 74M",
        "dennis_juba": "Lady's Well",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "-",
        "scarriff": "71M",
        "jh_stimpson": "-",
        "benson": "Blathnaid Smith",
        "church_bay": "Niall O'Dowda, Sonas",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "39",
        "year": "2014",
        "estemaid": "",
        "boyle": "Chang-Sha",
        "benjamin": "Desperado",
        "nm_barge": "-",
        "wynn_juba": "Peggy May, Adventure, David, Siobhain, Mick & Eilish",
        "jj_kineally": "MV Lady Lydia, 4E, Lady Diva, My Zen, Lady Jane, Lady Anne III",
        "friendship": "Matt McGrory",
        "bob_hughes": "McGrory Family Lady Diva",
        "ann_clarke": "Clodagh Lindley Lady Lydia",
        "newman": "Caja",
        "jimmy_leyden": "",
        "dennis_byrne": "-",
        "finton_harold": "-",
        "mccormack": "-",
        "dennis_juba": "R. Winston & F. Halfin Nancy J",
        "westpark": "Cormac Smith Coreibh",
        "eric_timon": "-",
        "tavern": "-",
        "scarriff": "4E",
        "jh_stimpson": "-",
        "benson": "Art Thornbury Auburn",
        "church_bay": "Fortune Family, Come on Eileen",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "38",
        "year": "2013",
        "estemaid": "",
        "boyle": "4B Jeffers",
        "benjamin": "ParadijsVogel",
        "nm_barge": "Trust Me Scout",
        "wynn_juba": "Gareth & Rory Kavanagh, Jack McGrory, Gearoid O'Brien",
        "jj_kineally": "74M, Carna Bay, Cottesway, Rambler, Schipperke",
        "friendship": "Liam Power",
        "bob_hughes": "Ellis Family Reflection",
        "ann_clarke": "Emily McGrory Lady Diva",
        "newman": "Michael Redmond & Family 57M",
        "jimmy_leyden": "Shanks Family, Serenity",
        "dennis_byrne": "Lindley Family Lady Lydia",
        "finton_harold": "A. Lindley Lady Lydia",
        "mccormack": "Shirley Mullins SeaCat",
        "dennis_juba": "R. Lindley Lady Lydia, A. Brislane Andante",
        "westpark": "D. Brislane Andante",
        "eric_timon": "Michael Campion",
        "tavern": "G. Burke",
        "scarriff": "68M",
        "jh_stimpson": "-",
        "benson": "Brian Boland Seagull",
        "church_bay": "Lindley Family, Lady Lydia",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "37",
        "year": "2012",
        "estemaid": "",
        "boyle": "68M",
        "benjamin": "El-Roi",
        "nm_barge": "Birling",
        "wynn_juba": "Ben Geraghty, Pearse Cavanagh, Reece Shortt",
        "jj_kineally": "El-Roi, Birling, Shanice, Namow V",
        "friendship": "Ellis Family",
        "bob_hughes": "Pat & Chrissie Mullins Caja",
        "ann_clarke": "Ben Geraghty Affaja",
        "newman": "Morgan O' Brien Family Cottesway",
        "jimmy_leyden": "E. Bayly & Family Crew's Inn",
        "dennis_byrne": "Leyden Family Mutual Admiration",
        "finton_harold": "C. Smith Coreibh",
        "mccormack": "Mary Burke Teanna",
        "dennis_juba": "D. Burke Affaja",
        "westpark": "D. Burke, C. Bayly Kigera",
        "eric_timon": "E. Bayly & D. Dunne Crew's Inn",
        "tavern": "D. Burke",
        "scarriff": "47M Palo Alto",
        "jh_stimpson": "-",
        "benson": "Anna Burke Teanna",
        "church_bay": "Leyden Family, Mutual Admiration",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "36",
        "year": "2011",
        "estemaid": "",
        "boyle": "4B Cliff & Eunice Jeffers",
        "benjamin": "Adventure",
        "nm_barge": "Shanog",
        "wynn_juba": "Ben Geraghty, Ed Campion, Pearse Cavanagh",
        "jj_kineally": "Affaja, Black Pearl, Carreras, Shanog, Teanna",
        "friendship": "Sophie Geraghty",
        "bob_hughes": "Colin & Genevieve Becker, Chang Sha",
        "ann_clarke": "Ciara Moore Lady Anne III",
        "newman": "-",
        "jimmy_leyden": "Andrew & Emma Clarke Double Dutch",
        "dennis_byrne": "Brislane Family Andante",
        "finton_harold": "M. Larkin Adventure",
        "mccormack": "J. Lambert De-Eems",
        "dennis_juba": "Scallywag (68M Crew)",
        "westpark": "P. & C. Mullins Caja",
        "eric_timon": "Ivan & Evie Thornbury Auburn",
        "tavern": "Reflection",
        "scarriff": "Chang Sha",
        "jh_stimpson": "-",
        "benson": "Robbie Saunders 41M",
        "church_bay": "Brislane Family, Andante",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "35",
        "year": "2010",
        "estemaid": "",
        "boyle": "4E Ben F. Treacy",
        "benjamin": "Teanna Tinca Tinca",
        "nm_barge": "Shanice",
        "wynn_juba": "Cliff & Andy Jeffers 4B",
        "jj_kineally": "4B, Chang Sha, De-Eems, Lotus 2, Affaja",
        "friendship": "Conor Nolan",
        "bob_hughes": "Gay Knight & S. Anne Argo",
        "ann_clarke": "Holly Farrell",
        "newman": "-",
        "jimmy_leyden": "68M, Tinca Tinca, 41M, Tanjuan",
        "dennis_byrne": "Hollinshead Family Serpa",
        "finton_harold": "M. Becker 74M",
        "mccormack": "-",
        "dennis_juba": "Kilmore Lass",
        "westpark": "C. Bayly Kigera",
        "eric_timon": "Sam Treacy 4E",
        "tavern": "-",
        "scarriff": "76M",
        "jh_stimpson": "-",
        "benson": "Ciara Moore Lady Anne III",
        "church_bay": "Hollinshead Family, Serpa",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "34",
        "year": "2009",
        "estemaid": "",
        "boyle": "4B Cliff & Eunice Jeffers",
        "benjamin": "Shanice",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "Seagull, Kobold, Shanice, Ocean Froggy",
        "friendship": "Brian Kavanagh",
        "bob_hughes": "Archie & Rita Reid Miss Eva",
        "ann_clarke": "-",
        "newman": "Ellis Family Reflection",
        "jimmy_leyden": "Kavanagh Family",
        "dennis_byrne": "-",
        "finton_harold": "G. Boland Seagull",
        "mccormack": "-",
        "dennis_juba": "Teanna Tinca Tinca",
        "westpark": "M. McGrory Lady Diva",
        "eric_timon": "Joe Treacy 4E",
        "tavern": "B. Treacy",
        "scarriff": "68M",
        "jh_stimpson": "-",
        "benson": "-",
        "church_bay": "-",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "33",
        "year": "2008",
        "estemaid": "",
        "boyle": "4E Ben F. Treacy",
        "benjamin": "Chang Sha",
        "nm_barge": "Magnet",
        "wynn_juba": "",
        "jj_kineally": "Chang Sha, Christina, Paragon,",
        "friendship": "Damien Buckley",
        "bob_hughes": "Colin & Genevieve Becker, Chang Sha",
        "ann_clarke": "-",
        "newman": "Kenny Family 76M",
        "jimmy_leyden": "-",
        "dennis_byrne": "Lowe Family Bare Necessities",
        "finton_harold": "G. Boland Seagull",
        "mccormack": "S. Mullins SeaCat",
        "dennis_juba": "Desparado",
        "westpark": "J. MacFarlane ParadjsVogel",
        "eric_timon": "Sam Treacy 4E",
        "tavern": "R. Lowe",
        "scarriff": "41M",
        "jh_stimpson": "-",
        "benson": "Ben F. Treacy 4E",
        "church_bay": "Lowe Family, Bare Necessities",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "32",
        "year": "2007",
        "estemaid": "",
        "boyle": "Dabu",
        "benjamin": "G. Burke",
        "nm_barge": "Trust Me Scout",
        "wynn_juba": "",
        "jj_kineally": "The Alamo, Shanice, Namow",
        "friendship": "Winston Family",
        "bob_hughes": "Robert & Maeve Bayly DABU",
        "ann_clarke": "-",
        "newman": "Winston Family Highlander",
        "jimmy_leyden": "-",
        "dennis_byrne": "Ellis Family Reflection",
        "finton_harold": "M. Larkin CastleFrench Lady",
        "mccormack": "A. Dwane 74M",
        "dennis_juba": "Peggy May, CastleFrech Lady, 4B, Double Dutch",
        "westpark": "B. & M. O' Brien Morning Mist",
        "eric_timon": "D. Burke, R Baker-Kenny, C. Bayly 107B",
        "tavern": "DABU",
        "scarriff": "Crew 107B",
        "jh_stimpson": "-",
        "benson": "Ciara McGowan Lotus Two",
        "church_bay": "Ellis Family, Reflection",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "31",
        "year": "2006",
        "estemaid": "",
        "boyle": "A. Dwane 74M",
        "benjamin": "Brian Kavanagh",
        "nm_barge": "Trust Me Scout",
        "wynn_juba": "",
        "jj_kineally": "Trust Me Scout, Truxton, Seacat, Teanna",
        "friendship": "Robert & Anne Clarke",
        "bob_hughes": "Archie & Rita Reid Miss Eva",
        "ann_clarke": "-",
        "newman": "Barry & Maire O' Brien Morning Mist",
        "jimmy_leyden": "Vincent, Catherine, David & John Garty Paragon",
        "dennis_byrne": "Rory & Luke Winston Highlander",
        "finton_harold": "-",
        "mccormack": "A. Dwane 74M",
        "dennis_juba": "Donal Boland M.V. James & Mary",
        "westpark": "C. Burke Teanna",
        "eric_timon": "S. O' Brolchain & Friends",
        "tavern": "D. Burke",
        "scarriff": "-",
        "jh_stimpson": "-",
        "benson": "Jennifer Jordan El-Roi",
        "church_bay": "Rory & Luke Winston, Highlander",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "30",
        "year": "2005",
        "estemaid": "",
        "boyle": "Chang-Sha Colin Becker",
        "benjamin": "-",
        "nm_barge": "Shanice",
        "wynn_juba": "",
        "jj_kineally": "74M, Grille, Escape & Emma Jane",
        "friendship": "Mullins Family",
        "bob_hughes": "41M Les Saunders & Yvonne Duffy",
        "ann_clarke": "-",
        "newman": "Archie & Rita Reed Nidders",
        "jimmy_leyden": "-",
        "dennis_byrne": "MacFarlanes ParadjsVogel",
        "finton_harold": "Sam Stephens Easy Beat",
        "mccormack": "A. Dwane 74M",
        "dennis_juba": "-",
        "westpark": "-",
        "eric_timon": "J. Jordan El-Roi",
        "tavern": "J. Leonard",
        "scarriff": "-",
        "jh_stimpson": "D. Killleen",
        "benson": "Ruth Bennett-Coady Pyladies",
        "church_bay": "MacFarlanes, ParadijsVogel",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "29",
        "year": "2004",
        "estemaid": "",
        "boyle": "Chang-Sha Colin Becker",
        "benjamin": "Goggin Family",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "Grille, 68M & Easy Beat",
        "friendship": "Robert & Anne Clarke",
        "bob_hughes": "-",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Goggin Family Knocknagow",
        "dennis_byrne": "-",
        "finton_harold": "D. O' Kinneda DABU",
        "mccormack": "S. Boyd Grille",
        "dennis_juba": "68M, Grille & Easy Beat",
        "westpark": "Grille, 68M & Easy Beat",
        "eric_timon": "Baker-Kenny 76M",
        "tavern": "Bayly's",
        "scarriff": "68M",
        "jh_stimpson": "-",
        "benson": "Mark Moore Lady Anne III",
        "church_bay": "-",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "28",
        "year": "2003",
        "estemaid": "",
        "boyle": "Dabu",
        "benjamin": "P. Nolan",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "Lady Anne III, 35M, NAMOW IV",
        "friendship": "Andy Roche",
        "bob_hughes": "-",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Tom & Dee Bailey & Crew Mimi",
        "dennis_byrne": "Aoife & Colm Burke",
        "finton_harold": "Joe Leonard",
        "mccormack": "A. Shanley Celtic Jade - A. Dwane Isolde",
        "dennis_juba": "M. Moore Lady Anne III, M. & J. Sweeney Elysium",
        "westpark": "P. Nolan Tinca Tinca",
        "eric_timon": "Sam Treacy 4E",
        "tavern": "Burke's",
        "scarriff": "-",
        "jh_stimpson": "-",
        "benson": "Mark Moore Lady Anne III",
        "church_bay": "-",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "27",
        "year": "2002",
        "estemaid": "",
        "boyle": "34B Gerry Gavin, Chang-Sha Colin Becker",
        "benjamin": "P. & J. Timon, T. & N. McGowan",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "Jasmine, 68M & Time Enough",
        "friendship": "-",
        "bob_hughes": "-",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Gerry & Geraldine Burke & Crew 68M",
        "dennis_byrne": "D. & J. Cullen Corncrake",
        "finton_harold": "Bayly DABU",
        "mccormack": "G. Burke 68M J. Ray Chang-Sha",
        "dennis_juba": "Bayly DABU",
        "westpark": "68M, Jasmine & Time Enough",
        "eric_timon": "The Burke's 68M",
        "tavern": "-",
        "scarriff": "-",
        "jh_stimpson": "-",
        "benson": "Ciara Moore Jasmine",
        "church_bay": "D & J Cullen, Corkcrake",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "26",
        "year": "2001",
        "estemaid": "",
        "boyle": "35M Andy Roche",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "A. & G. Roberts Merganser",
        "friendship": "-",
        "bob_hughes": "A. & G. Roberts Merganser",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Tom Moore, Eamon Egan Jasmine & Hawthorn",
        "dennis_byrne": "McGrane Family Sally",
        "finton_harold": "-",
        "mccormack": "P. Stephens Yali",
        "dennis_juba": "Louise Egan Hawthorn, Ciara Moore Jasmine",
        "westpark": "A. & G. Roberts Merganser",
        "eric_timon": "-",
        "tavern": "A. & G. Roberts",
        "scarriff": "St. Patrick",
        "jh_stimpson": "-",
        "benson": "Daniel Burke 68M",
        "church_bay": "McGrane Family, Sally",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "25",
        "year": "2000",
        "estemaid": "",
        "boyle": "4E Joe Treacy",
        "benjamin": "R. Carton & A. Hynes",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "The Beckers Isolde",
        "friendship": "-",
        "bob_hughes": "McCool Family Snark",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Michael Devlin Beccles",
        "dennis_byrne": "Greevy's Aine",
        "finton_harold": "-",
        "mccormack": "C. Tucker De-Eems",
        "dennis_juba": "Aine & 68M",
        "westpark": "E McLoughney Aquila Nova",
        "eric_timon": "Brian Goggin",
        "tavern": "-",
        "scarriff": "Neptune",
        "jh_stimpson": "-",
        "benson": "Olivia Egan Hawthorn",
        "church_bay": "Greevy Family, Aine",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "P. Cagney Desiree",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "24",
        "year": "1999",
        "estemaid": "",
        "boyle": "De Eems P. Clarke-Hutton",
        "benjamin": "E. Keane",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "DABU",
        "friendship": "-",
        "bob_hughes": "Robert & Maeve Bayly DABU",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Roger & Stef Lorenz Neptune",
        "dennis_byrne": "Baker-Kenny 76M",
        "finton_harold": "Joe Leonard",
        "mccormack": "Angela Dwane Chang-Sha",
        "dennis_juba": "N. Kerrigan Yali",
        "westpark": "C. Bayly",
        "eric_timon": "E. & P.J. Norris Jangada",
        "tavern": "G. Burke",
        "scarriff": "4E",
        "jh_stimpson": "C. Makin & S. Hopkins",
        "benson": "Ciara O'Brien Palo Alto",
        "church_bay": "Baker-Kenny Family, 76M",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "Early Dawn",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "23",
        "year": "1998",
        "estemaid": "",
        "boyle": "Dabu",
        "benjamin": "E. Bayly & K. Kendrick",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "-",
        "friendship": "-",
        "bob_hughes": "Andy & Cathy Roche 35M",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "-",
        "dennis_byrne": "Dywer Laura James",
        "finton_harold": "John Treacey",
        "mccormack": "Christine Becker Chang- Sha",
        "dennis_juba": "-",
        "westpark": "C. Bayly DABU",
        "eric_timon": "-",
        "tavern": "J. Treacy",
        "scarriff": "DABU",
        "jh_stimpson": "C. Becker & G. Bayly",
        "benson": "Paul Makim Sunset",
        "church_bay": "Dywer Family",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "Paddy McLoughney Aquila Nova",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "22",
        "year": "1997",
        "estemaid": "",
        "boyle": "35M Andy Roche",
        "benjamin": "E. & C. Bayly",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "DABU",
        "friendship": "-",
        "bob_hughes": "Tos & Ann Quinn Abigail",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Joe Leonard & Lana Tracey, Shanice",
        "dennis_byrne": "Ciaran Goggin",
        "finton_harold": "R. Moore Jasmine",
        "mccormack": "-",
        "dennis_juba": "-",
        "westpark": "-",
        "eric_timon": "P. Moore Jasmine",
        "tavern": "J. Leonard",
        "scarriff": "DABU",
        "jh_stimpson": "Eoin Bayly",
        "benson": "-",
        "church_bay": "Goggin Family",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "Ged Molloy Siou Eile",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "21",
        "year": "1996",
        "estemaid": "",
        "boyle": "Chang-Sha Sharon O' Grady",
        "benjamin": "C. O'Brien",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "Early Dawn",
        "friendship": "-",
        "bob_hughes": "Peter Cagney Celtic Jade",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Noel & June Manning & Crew Coral Star",
        "dennis_byrne": "Roche Family 35M",
        "finton_harold": "C. Becker Chang Sha",
        "mccormack": "-",
        "dennis_juba": "Bayly, DABU",
        "westpark": "-",
        "eric_timon": "Moores on 20 Pence",
        "tavern": "M. O' Riordan",
        "scarriff": "47M Palo Alto",
        "jh_stimpson": "Christine Becker",
        "benson": "Aisling Moore Jasmine",
        "church_bay": "Roche Family, 35M",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "Brendan Hassett Condor",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "20",
        "year": "1995",
        "estemaid": "",
        "boyle": "Dabu",
        "benjamin": "R. Bayley & F. Dwane",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "Early Dawn",
        "friendship": "-",
        "bob_hughes": "Michael O' Riordan Early Dawn",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Joe Treacy & Crew 4E",
        "dennis_byrne": "-",
        "finton_harold": "P. O' Brien Palo Alto",
        "mccormack": "-",
        "dennis_juba": "-",
        "westpark": "P. Kelehan Viv___",
        "eric_timon": "J. & S. Treacy 4E",
        "tavern": "M. O' Riordan",
        "scarriff": "47M Palo Alto",
        "jh_stimpson": "Pam O' Brien",
        "benson": "E. McLoughney Aquila Nova",
        "church_bay": "-",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "19",
        "year": "1994",
        "estemaid": "",
        "boyle": "Sequoia Jack Roberts",
        "benjamin": "A. & R. Pearson",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "Downes Family Sapphire",
        "friendship": "-",
        "bob_hughes": "-",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Eamon Egan & Crew Hawthorn",
        "dennis_byrne": "The Moore's Twenty Pence",
        "finton_harold": "C. Becker Chang Sha",
        "mccormack": "J. Craig A. Felion Calypso",
        "dennis_juba": "-",
        "westpark": "P. Smith Tubal",
        "eric_timon": "Mayfly",
        "tavern": "J. Roberts",
        "scarriff": "Calypso",
        "jh_stimpson": "-",
        "benson": "J. Craig & A. Felton Calypso",
        "church_bay": "Moore Family, Twenty Pence",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "18",
        "year": "1993",
        "estemaid": "",
        "boyle": "Palo Alto P. O' Brien",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "The O' Briens Palo Alto",
        "friendship": "-",
        "bob_hughes": "Tos Quinn Abigail",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "-",
        "dennis_byrne": "-",
        "finton_harold": "J. Bagnall 76M",
        "mccormack": "M. Hanna Lady Penlyric",
        "dennis_juba": "-",
        "westpark": "D. & S. Talbot Rindoon Rose",
        "eric_timon": "Chang Sha",
        "tavern": "E. Ganly",
        "scarriff": "Sequoia",
        "jh_stimpson": "-",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "17",
        "year": "1992",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "D. Pearson Moody",
        "friendship": "-",
        "bob_hughes": "Peter & Mary Hanna,  Lady Penlyric",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Gary Kelly & Mary",
        "dennis_byrne": "-",
        "finton_harold": "J. Fitzgibbon Brigade",
        "mccormack": "B. Fitzgibbon Brigade",
        "dennis_juba": "T. Gallagher __NOT SURE WHAT YEAR!!__",
        "westpark": "D. Becker Chang Sha",
        "eric_timon": "Whitethorn",
        "tavern": "M. O' Brien",
        "scarriff": "Sequoia",
        "jh_stimpson": "The Henry's",
        "benson": "Daniel Becker Chang-Sha",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "16",
        "year": "1991",
        "estemaid": "",
        "boyle": "MV Fox Syd Shine",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "T. MacBride Kid",
        "friendship": "-",
        "bob_hughes": "Padriac O' Brolchain Barcarole",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "-",
        "dennis_byrne": "-",
        "finton_harold": "C. Becker Chang Sha",
        "mccormack": "M. O' Brien Adventurer",
        "dennis_juba": "-",
        "westpark": "V. & P. Henry Paloma",
        "eric_timon": "Abigail & Ajenda",
        "tavern": "-",
        "scarriff": "-",
        "jh_stimpson": "Albert Gill",
        "benson": "Marcus Quinn Abigail",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "15",
        "year": "1990",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "-",
        "friendship": "-",
        "bob_hughes": "-",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Pat & Margaret McLoughney & The Mini Crew",
        "dennis_byrne": "-",
        "finton_harold": "-",
        "mccormack": "-",
        "dennis_juba": "D. & K. Killeen Gillaroo",
        "westpark": "D. Killeen Gillaroo",
        "eric_timon": "Sequoia",
        "tavern": "-",
        "scarriff": "-",
        "jh_stimpson": "-",
        "benson": "Marcus Quinn Abigail",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "14",
        "year": "1989",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "K. Walsh Santa Royale",
        "friendship": "-",
        "bob_hughes": "-",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Seamus Kerrigan & Crew",
        "dennis_byrne": "M. Leyden Sheba",
        "finton_harold": "-",
        "mccormack": "M. Hanna Lady Penlyric",
        "dennis_juba": "S. Anne Hamilton Jacaranda",
        "westpark": "P. & J. Gilmore Shannon Rose",
        "eric_timon": "41M",
        "tavern": "T. Mac Bride",
        "scarriff": "Sequoia",
        "jh_stimpson": "Jason Gilmour",
        "benson": "Richard Hodgins 34M",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "13",
        "year": "1988",
        "estemaid": "",
        "boyle": "Chang-Sha Colin Becker",
        "benjamin": "P. Keane",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "J. Horan Winsome Wings",
        "friendship": "-",
        "bob_hughes": "J. Horan Winsome Wings",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "Tiernan MacBride & Sarah",
        "dennis_byrne": "D. Saunders 41M",
        "finton_harold": "A. Craig Bolero",
        "mccormack": "R. Martin Dunboyne",
        "dennis_juba": "C. Benson Ajenda",
        "westpark": "J. Horan Winsome Wings",
        "eric_timon": "Do Do M",
        "tavern": "B. O' Brien",
        "scarriff": "-",
        "jh_stimpson": "J. & E. Tomlin",
        "benson": "Gerard Keane Whitethorn",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "12",
        "year": "1987",
        "estemaid": "",
        "boyle": "De Eems P. Clarke-Hutton",
        "benjamin": "D. Cagney & R. Cagney",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "J. Roberts Sequoia",
        "friendship": "-",
        "bob_hughes": "C. Scotson Ajenda",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "A. Roberts Sequoia",
        "finton_harold": "J. Horan Winsome Wings",
        "mccormack": "A. Craig Bolero",
        "dennis_juba": "G. Brislane Vitesse",
        "westpark": "J. Roberts Sequoia",
        "eric_timon": "Do Do M",
        "tavern": "J. DuMoulin",
        "scarriff": "Sequoia",
        "jh_stimpson": "St. Patrick",
        "benson": "George Roberts Sequoia",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "11",
        "year": "1986",
        "estemaid": "",
        "boyle": "Sequoia J McLean-Roberts",
        "benjamin": "I. Travers & N. Fleeton",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "M. Maguire Maan of Derg",
        "friendship": "-",
        "bob_hughes": "Sequoia J. Roberts",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "M. Maguire Jnr. Maan of Derg",
        "finton_harold": "N. Waterhouse Lady Rona",
        "mccormack": "D. Horan Winsome Wings",
        "dennis_juba": "-",
        "westpark": "J. Reynolds Wine Lake",
        "eric_timon": "Abigail, Ajenda & Whitethorn",
        "tavern": "C. Scotson",
        "scarriff": "M.B. Jarra",
        "jh_stimpson": "Galen Brislane",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "10",
        "year": "1985",
        "estemaid": "",
        "boyle": "JARRA",
        "benjamin": "G. Brislane",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "T. Keane Whitethorn",
        "friendship": "-",
        "bob_hughes": "T. Quinn Abigail",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "G. Brislane Vitesse",
        "finton_harold": "N. Larlin Argo",
        "mccormack": "J. Leydon Geraldine II",
        "dennis_juba": "T. Quinn Abigail",
        "westpark": "N. Waterhouse Lady Rona",
        "eric_timon": "Sue O' Brolchain",
        "tavern": "P. O Brolchain",
        "scarriff": "66M Bishop Whelan",
        "jh_stimpson": "-",
        "benson": "D. Collins",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "9",
        "year": "1984",
        "estemaid": "",
        "boyle": "JARRA",
        "benjamin": "B. Henderson & G. Brislane",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "R. Henneson Mary Frances",
        "friendship": "-",
        "bob_hughes": "R. Henderson, Mary Frances",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "M. Williams Shanra",
        "finton_harold": "L. Benson Marlou",
        "mccormack": "D. Horan Sandpiper",
        "dennis_juba": "D. Brislane Lady Sarah",
        "westpark": "P.J. Humphries Blue Moon",
        "eric_timon": "-",
        "tavern": "D. Brislane",
        "scarriff": "-",
        "jh_stimpson": "-",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "8",
        "year": "1983",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "E. & A. Bracken",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "-",
        "friendship": "-",
        "bob_hughes": "-",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "Ian Kelly Siam III",
        "finton_harold": "P. MacNamara Moonshine",
        "mccormack": "-",
        "dennis_juba": "R. Henderson Janey Mac",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "S. Herraghty",
        "scarriff": "Argo",
        "jh_stimpson": "-",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "7",
        "year": "1982",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "M. Fleeton & G. Brislane",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "-",
        "friendship": "-",
        "bob_hughes": "-",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "-",
        "finton_harold": "B. O' Reilly Porter's Eve",
        "mccormack": "-",
        "dennis_juba": "-",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "A. Dier",
        "scarriff": "4E",
        "jh_stimpson": "David Dier",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "6",
        "year": "1981",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "R. Benson Marlou",
        "friendship": "-",
        "bob_hughes": "J. Fitzgibbon M.S. Bilbo",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "D.J. Harrison J.F. Aylmer Eagle",
        "finton_harold": "N. Hodgers Aine",
        "mccormack": "-",
        "dennis_juba": "R. Benson Marlou",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "-",
        "scarriff": "Sequoia",
        "jh_stimpson": "-",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "5",
        "year": "1980",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "-",
        "friendship": "-",
        "bob_hughes": "Christa Lilge, Hein Goodewind II",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "-",
        "finton_harold": "D. Knight Itty Three",
        "mccormack": "-",
        "dennis_juba": "S. Fitzsimons Ye Iron Lung",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "-",
        "scarriff": "Ye Iron Lung",
        "jh_stimpson": "-",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "",
        "year": "1979",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "No Rally (Low Water)",
        "friendship": "-",
        "bob_hughes": "No Rally (Low Water)",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "No Rally (Low Water)",
        "finton_harold": "No Rally (Low Water)",
        "mccormack": "-",
        "dennis_juba": "No Rally (Low Water)",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "No Rally (Low Water)",
        "scarriff": "No Rally (Low Water)",
        "jh_stimpson": "No Rally (Low Water)",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "4",
        "year": "1978",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "-",
        "friendship": "-",
        "bob_hughes": "J.B.H. Johnston, De-Eems",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "Harbour Belle",
        "finton_harold": "J. Roberts Mallard",
        "mccormack": "-",
        "dennis_juba": "D.  Killeen",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "J. Treacey",
        "scarriff": "DABU",
        "jh_stimpson": "M. Webb Jnr.",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "3",
        "year": "1977",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "-",
        "friendship": "-",
        "bob_hughes": "P. Dowling Eistemaid",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "S. & B. Bayly DABU",
        "finton_harold": "R. Benson Marlou",
        "mccormack": "-",
        "dennis_juba": "S. McGloughney Elf",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "M. Mathews",
        "scarriff": "M.V. Fox",
        "jh_stimpson": "-",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "2",
        "year": "1976",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "R. Hughes Margarita II",
        "friendship": "-",
        "bob_hughes": "D.G. & A.A. Bain, M.S. Janey Mac",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "-",
        "finton_harold": "Fitzgibbon Bilbo",
        "mccormack": "-",
        "dennis_juba": "P. Dowling Estemaid",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "R. Hughes",
        "scarriff": "M.V. St. Patrick",
        "jh_stimpson": "-",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    },
    {
        "rally": "1",
        "year": "1975",
        "estemaid": "",
        "boyle": "-",
        "benjamin": "-",
        "nm_barge": "-",
        "wynn_juba": "",
        "jj_kineally": "M. McInerney Scalpa M/Y",
        "friendship": "-",
        "bob_hughes": "D.G. & A.A. Bain, T.S.D.Y. Cuanna",
        "ann_clarke": "-",
        "newman": "",
        "jimmy_leyden": "",
        "dennis_byrne": "-",
        "finton_harold": "-",
        "mccormack": "-",
        "dennis_juba": "S. Kerrigan St. Patrick",
        "westpark": "-",
        "eric_timon": "-",
        "tavern": "R. Hughes",
        "scarriff": "Scalpa M/Y",
        "jh_stimpson": "-",
        "benson": "-",
        "church_bay": "",
        "derg_cup": "",
        "goosander": "",
        "oconnor": "",
        "jane_mccormack_trophy": "-",
        "skelton_remembrance": "",
        "dave_mccabe": ""
    }
];